# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OhMyBoxSellersIos' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Fabric'
    pod 'Crashlytics'
  # Pods for OhMyBoxSellersIos

  target 'OhMyBoxSellersIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
