# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OhMyBoxSellersIos' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'FalconFrameworkIOSSDK', :git => 'https://gitlab.com/LAB262/FalconFrameworkIOSSDK.git'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Storage'
    pod 'SDWebImage', '~>3.8'

  target 'OhMyBoxSellersIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
