# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'


def common_pods
    
    use_frameworks!
    inhibit_all_warnings!

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'SDWebImage', '~>3.8'
end

target 'lab262.ohmybox.sales.dev' do
    common_pods
end

target 'lab262.ohmybox.sales.test' do
    common_pods
end

target 'lab262.ohmybox.sales.production' do
    common_pods
end

target 'OhMyBoxSellersIosTests' do
    inherit! :search_paths
    common_pods
end
